[versions]
kotlin = "2.2.20"
dokka = "2.1.0"
shadow = "9.3.0"
paper = "1.21-R0.1-SNAPSHOT"
paperweight = "2.0.0-beta.19"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
